site_name: Programaci칩n de Aplicaciones M칩viles Nativas
site_url: https://mltechbox.github.io/PAMN/
repo_url: https://github.com/Mltechbox/PAMN
theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Inicio: index.md
  - Temario:
      - Bloque 1:
          - Introducci칩n: Temario/Bloque1/index.md
          - Arquitectura y ciclo de vida: Temario/Bloque1/01-arquitectura-y-ciclo-de-vida.md
          - Accesibilidad y normativa: Temario/Bloque1/02-accesibilidad-y-normativa.md
          - Dise침o de interfaces: Temario/Bloque1/03-diseno-interfaces-usuario.md
